config/routes.rb
Gadgets::Application.routes.draw do
  devise_for :users

  root to: 'home#index'
  get '/gadgets' => 'gadgets#index', as: :user_root

  resources :gadgets
end

app/models/gadget.rb
class Gadget < ActiveRecord::Base
  scope :filter_by_name, ->(name){where("name LIKE '#{name}%'")}

  validates_presence_of :name

  mount_uploader :image, GadgetImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :gadgets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/gadgets_controller.rb
class GadgetsController < InheritedResources::Base
  before_filter :authenticate_user!
 
  def create
    create!{gadgets_path}
  end

  protected
  def begin_of_association_chain
    current_user
  end

  def collection
    if params[:gadget].try(:[], :filter)
      @gadgets ||= end_of_association_chain.filter_by_name(params[:gadget][:filter])
    else
      super
    end
  end

  def build_resource_params
    [params.fetch(:gadget, {}).permit(:name, :description, :image)]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to user_root_path if current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/gadgets/_filter.html.erb
<%= simple_form_for Gadget.new, url: gadgets_path(mode: params[:mode]), method: :get, class: 'form-search'  do |f| %>
  <%= f.input_field :filter, value: params[:gadget].try(:[], :filter), class: 'search-query' %>
  <%= f.submit t('.search'), class: 'btn'  %>
<% end %>

app/views/gadgets/_gadget.html.erb
<% if params[:mode] == 'list_mode' %>
  <li class="gadget_list_mode">
    <span><%= gadget.name %></span>
    <span><%= gadget.name %></span>
  </li>
<% else %>
  <li class="thumbnail gadget_cover_flow">
    <div><%= image_tag gadget.image.thumb.url %></div>
    <div class="caption"><%= gadget.name %></div>
  </li>
<% end %>

app/views/gadgets/index.html.erb
<div class="row-fluid">
  <div class="span4">
    <%= render 'filter' %>
  </div>

  <div id='view_mode' class="btn-group span4">
    <% if !params[:mode] || params[:mode] == 'cover_flow' %>
      <span class="active btn"><%= t('.cover_flow') %></span>
      <span class="btn">
        <%= link_to t('.list_mode'), gadgets_path(mode: 'list_mode', gadget: {filter: params[:gadget].try(:[], :filter)}) %>
      </span>
    <% else %>
      <span class="btn">
        <%= link_to t('.cover_flow'), gadgets_path(mode: 'cover_flow', gadget: {filter: params[:gadget].try(:[], :filter)}) %>
      </span>
      <span class="active btn"><%= t('.list_mode') %></span>
    <% end %>
  </div>
</div>

<ul class="<%= !params[:mode] || params[:mode] == 'cover_flow' ? 'thumbnails' : 'unstyled' %>">
  <%= render @gadgets %>
</ul>

<%= link_to t('.add_new_gadget_lnk'), new_gadget_path, class: 'btn' %>

app/views/gadgets/new.html.erb
<%= simple_form_for @gadget, html: {class: "form-horizontal"} do |f| %>
  <div class="control-group">
    <%= f.input :name %>
    <%= f.input :description, as: :text, input_html: {rows: 5} %>
    <%= f.input  :image, as: :file %>
  </div>
  <div class="control-group">  
    <%= f.submit t('.create_gadget'), class: 'btn btn-large' %>
  </div>
<% end %>

app/views/home/index.html.erb
<div class="button-group">
  <%= link_to t('.sign_in'), new_user_session_path, class: 'btn btn-large' %>
  <%= link_to t('.sign_up'), new_user_registration_path, class: 'btn btn-large' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gadgets</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%# -- Navigation bar -- %>
  <div class="container navbar">
    <div class="brand">
      <%= link_to t('.brand'), root_path %>
    </div>
    <% if user_signed_in? %>
      <%= link_to t('.sign_out'), destroy_user_session_path, method: :delete, class: 'btn' %>
    <% end %>
  </div>
  <%# -- Navigation bar -- %>
  
  <div class="container">
    <p class="notice alert-info"><%= notice %></p>
    <p class="alert-danger"><%= alert %></p>

    <%= yield %>
  </div>
</body>
</html>